<?php
namespace app\modules\shopee\controllers;

use yii\web\Controller;

class ProductController extends Controller{

    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionCreate(){

    }

    public function actionUpdate(){


    }

    public function actionAll(){

    }

    public function actionList($account=''){


    }

    public function actionDelete(){

    }
}
